# Generated by Django 4.2 on 2026-07-08 00:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, unique=True, verbose_name='اسم المرض بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرض بالإنجليزية')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل للعرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'مرض',
                'verbose_name_plural': 'الأمراض',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='اسم الطبيب بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الطبيب بالإنجليزية')),
                ('specialty_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص بالعربية')),
                ('specialty_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص بالإنجليزية')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الترخيص الطبي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'طبيب',
                'verbose_name_plural': 'الأطباء',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=150, verbose_name='اسم المستشفى بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المستشفى بالإنجليزية')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مستشفى',
                'verbose_name_plural': 'المستشفيات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=30, unique=True, verbose_name='الرقم التسلسلي')),
                ('leave_type', models.CharField(choices=[('حكومي', 'حكومي'), ('خاص', 'خاص'), ('شعار', 'شعار')], default='حكومي', max_length=10, verbose_name='نوع الإجازة')),
                ('custom_disease', models.TextField(blank=True, null=True, verbose_name='المرض المخصص (نص حر)')),
                ('date_in', models.DateField(blank=True, null=True, verbose_name='تاريخ الدخول (ميلادي)')),
                ('date_in_formatted', models.CharField(blank=True, max_length=20, null=True, verbose_name='التاريخ المنسق للدخول')),
                ('date_in_hijri', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاريخ الدخول (هجري)')),
                ('week_day', models.CharField(blank=True, max_length=20, null=True, verbose_name='يوم الأسبوع')),
                ('date_out', models.DateField(blank=True, null=True, verbose_name='تاريخ الخروج (ميلادي)')),
                ('date_out_formatted', models.CharField(blank=True, max_length=20, null=True, verbose_name='التاريخ المنسق للخروج')),
                ('date_out_hijri', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاريخ الخروج (هجري)')),
                ('days_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد الأيام')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إصدار التقرير')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تقرير طبي',
                'verbose_name_plural': 'التقارير الطبية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(help_text='رقم الهوية الوطنية أو رقم الإقامة', max_length=20, unique=True, verbose_name='رقم الهوية / الإقامة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم الرباعي بالعربية')),
                ('name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالإنجليزية')),
                ('nationality_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية بالعربية')),
                ('nationality_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='الجنسية بالإنجليزية')),
                ('relationship_ar', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة بالعربية')),
                ('relationship_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة بالإنجليزية')),
                ('employer', models.CharField(blank=True, max_length=150, null=True, verbose_name='جهة العمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مريض',
                'verbose_name_plural': 'المرضى',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, verbose_name='المستشفى الرئيسي؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_reports', to='reports.hospital', verbose_name='المستشفى')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_hospitals', to='reports.medicalreport', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'مستشفى التقرير',
                'verbose_name_plural': 'مستشفيات التقارير',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='الطبيب الرئيسي؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_reports', to='reports.doctor', verbose_name='الطبيب')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_doctors', to='reports.medicalreport', verbose_name='التقرير')),
            ],
            options={
                'verbose_name': 'طبيب التقرير',
                'verbose_name_plural': 'أطباء التقارير',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['national_id'], name='reports_pat_nationa_33ede5_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name_ar'], name='reports_pat_name_ar_d195bc_idx'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='disease_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.disease', verbose_name='المرض المختار من القائمة'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='doctors',
            field=models.ManyToManyField(related_name='reports', through='reports.ReportDoctor', to='reports.doctor', verbose_name='الأطباء'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='hospitals',
            field=models.ManyToManyField(related_name='reports', through='reports.ReportHospital', to='reports.hospital', verbose_name='المستشفيات'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='reports.patient', verbose_name='المريض'),
        ),
        migrations.AlterUniqueTogether(
            name='reporthospital',
            unique_together={('report', 'hospital')},
        ),
        migrations.AlterUniqueTogether(
            name='reportdoctor',
            unique_together={('report', 'doctor')},
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['serial_no'], name='reports_med_serial__0e635f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['date_in', 'date_out'], name='reports_med_date_in_0e51da_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalreport',
            index=models.Index(fields=['patient', 'date_in'], name='reports_med_patient_871e2a_idx'),
        ),
    ]
