# Generated by Django 4.2 on 2026-07-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_medicalreport_barcode_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='name_ar_ar',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='اسم المرض بالعربية'),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_ar_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='اسم المرض بالعربية'),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_en_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرض بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='disease',
            name='name_en_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المرض بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_ar_ar',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم الطبيب بالعربية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_ar_en',
            field=models.CharField(max_length=100, null=True, verbose_name='اسم الطبيب بالعربية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_en_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الطبيب بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='name_en_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الطبيب بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_ar_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص بالعربية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_ar_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص بالعربية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_en_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty_en_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التخصص بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_ar_ar',
            field=models.CharField(max_length=150, null=True, verbose_name='اسم المستشفى بالعربية'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_ar_en',
            field=models.CharField(max_length=150, null=True, verbose_name='اسم المستشفى بالعربية'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_en_ar',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المستشفى بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name_en_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='اسم المستشفى بالإنجليزية'),
        ),
    ]
