# Generated by Django 4.2 on 2026-07-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_disease_name_ar_ar_disease_name_ar_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='name_ar_ar',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='name_ar_en',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='name_en_ar',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='name_en_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name_ar_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name_ar_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name_en_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='name_en_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty_ar_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty_ar_en',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty_en_ar',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialty_en_en',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name_ar_ar',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name_ar_en',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name_en_ar',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name_en_en',
        ),
    ]
