# Generated by Django 4.2 on 2026-07-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_disease_name_ar_ar_remove_disease_name_ar_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='hospital_name_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المستشفى بالعربية'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='hospital_name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المستشفى بالإنجليزية'),
        ),
    ]
