# Generated by Django 4.2 on 2026-07-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_medicalreport_hospital_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='hospital_name_ar',
        ),
        migrations.RemoveField(
            model_name='medicalreport',
            name='hospital_name_en',
        ),
    ]
