# Generated by Django 4.2 on 2026-07-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_medicalreport_hospital_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_logos/', verbose_name='شعار المستشفى'),
        ),
    ]
