# Generated by Django 4.2 on 2026-08-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_hospital_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إذا كان غير نشط، لن يظهر في نتائج الاستعلام', verbose_name='التقرير نشط'),
        ),
    ]
